configs:
  # === MISC CONFIGURATION ===
  misc:
    seed: 2047315 # Seed for reproducibility
    topK: 3
    image: "car-color-classifier/data/output2.jpg"
  # === COLOR CLASSIFIER CONFIGURATION ===
  color_classifier:
    model_file: "car-color-classifier/models/model-weights-spectrico-car-colors-recognition-mobilenet_v3-224x224-180420.pb"
    label_file: "car-color-classifier/labels.txt" # color_classifier
    input_layer: "input_1"
    output_layer: "Predictions/Softmax/Softmax"
    input_size: [224, 224]
  # === TYPE CLASSIFIER CONFIGURATION ===
  type_classifier:
    model_file: "car-color-classifier/models/model-weights-spectrico-mmr-mobilenet-128x128-344FF72B.pb"
    label_file: "car-color-classifier/model_labels.txt" # model_type_classifier
    input_layer: "input_1"
    output_layer: "softmax/Softmax"
    input_size: [128, 128]