reid: 
  dataset:
    data_path: "data"
    dataset_name: "veri-776"
    dataset_size: "small"

  model:
    model: "resnet50"
    pretrained: true,
    device: "cuda"
    model_val_path: "model_ep-180_loss-0.0023.pth"

  loss:
    alpha: 0.9
    k: 500
    margin: 0.3
    label_smoothing: 0.1
    apply_MALW: True

  training:
    epochs: 200
    batch_size: 32
    learning_rate: 3.5e-4
  
  validation:
    batch_size: 32
    val_interval: 5

  test:
    normalize_embeddings: False
    run_reid_metrics: True
