reid:
  # === DATASET CONFIGURATION ===
  dataset:
    data_path: "data"
    dataset_name: "veri-776"
    dataset_size: "small"

  # === MODEL CONFIGURATION ===
  model:
    model: "resnet50"
    pretrained: True
    device: "cuda:0"
    use_gem: False
    use_stride: False
    use_bottleneck: False

  # === LOSS CONFIGURATION ===
  loss:
    alpha: 0.9
    k: 500
    margin: 0.3
    label_smoothing: 0.0
    apply_MALW: False

  # === TRAINING CONFIGURATION ===
  training:
    epochs: 260
    batch_size: 36
    num_workers: 8
    output_dir: "results"
    # ===> Optimizer configuration
    learning_rate: 1.5e-4
    bias_lr_factor: 2
    weight_decay: 0.0005
    weight_decay_bias: 0.0001
    # ===> Scheduler configuration (WarmupDecayLR)
    use_warmup: False
    steps: [20, 30, 45, 60, 75, 90, 105, 120, 135, 150, 165, 180, 195, 210, 225, 240, 255]
    warmup_gamma: 0.6
    warmup_epochs: 10
    decay_method: "linear"
    log_interval: 100
    # ===> Loading checkpoint
    load_checkpoint: False # Could be also a path to a checkpoint

  # === VALIDATION CONFIGURATION ===
  validation:
    batch_size: 16
    val_interval: 5

  # === TEST CONFIGURATION ===
  test:
    normalize_embeddings: False
    run_reid_metrics: True
    model_val_path: "model_ep-2_loss-1.0532.pth"