yolov8: 
 # -- GENERAL -- #
 main:
  video_path: 'tracking\video\video_traffic_2.mp4'
  disp_infos: True
  save_video: True

 # -- MODEL -- #
 model:
  yolo_model_name: 'yolov8n'
  tracked_class: {1: 'bicycle', 2: 'car', 3: 'motorcycle', 5: 'bus', 6: 'train', 7: 'truck'}
  downscale_factor: 4
  confidence_threshold: 0.1