# === MISC CONFIGURATION ===
MISC:
  OUTPUT_DIR: "results_test"
  DEVICE: "cuda"
  GPU_ID: 0

# === DATASET CONFIGURATION ===
REID:
  DATASET:
    DATA_PATH: "./data"
    DATASET_NAME: ['vric', 'ai_city', 'ai_city_sim'] # ai_city / ai_city_mix / ai_city_sim / vehicle_id / veri_776 / veri_wild / vric / vru
    SPLITTINGS: [('vric', 0.2481), ('ai_city', 0.3528), ('ai_city_sim', 0.026)] # Only to be adjusted if dataset_name is a list (CombinedDataset)
    DATASET_SIZE: "small" # small / medium / large
    SAMPLER_TYPE: "random" # random / balanced / None
    NUM_INSTANCES: 6 # Only to be adjusted if sampler_type is either "random" or "balanced"

  # === MODEL CONFIGURATION ===
  MODEL:
    NAME: "resnet50_ibn_a" # "resnet50" / "resnet101" / "resnet50_ibn_a" / "resnet101_ibn_a"
    PRETRAINED: True
    USE_GEM: False
    USE_STRIDE: True
    USE_BOTTLENECK: True

  # === COLOR CLASSIFIER CONFIGURATION ===
  COLOR_MODEL:
    NAME: "efficientnet-b5" # "svm" / "efficientnet-b3" / "efficientnet-b5" (our implementation)
    PRETRAINED_PATH: "./tracking/car-color-classifier/Models/EfficientNet-B5_loss-0.2239_acc-94.0872.pt"
    #PRETRAINED_PATH: "./tracking/car-color-classifier/Models/svm_classifier_v3.pkl"

  # === VALIDATION CONFIGURATION ===
  VALIDATION:
    BATCH_SIZE: 16
    RE_RANKING: True
    VISUALIZE_RANKS: False

  # === TEST CONFIGURATION ===
  TEST:
    TESTING: True # Always set to True (in config_test.yml) to avoid training the model etc.
    NORMALIZE_EMBEDDINGS: True
    RUN_REID_METRICS: False
    RUN_COLOR_METRICS: False
    PRINT_CONFUSION_MATRIX: False # Only available if run_color_metrics is True
    STACK_IMAGES: True # Stack all the images to create a NxN matrix of similarity scores. Only available if run_reid_metrics is False and run_color_metrics is False
    PATH_IMG_1: "./data/test/honda_f.jpg"
    PATH_IMG_2: "./data/test/honda_f_2.jpg"
    SIMILARITY_ALGORITHM: "cosine" # "euclidean" / "cosine"
    MODEL_VAL_PATH: "./reid/results/Test-14/model_ep-158_loss-0.0275.pth"